"""init

Revision ID: 5d9095a83710
Revises: 
Create Date: 2021-08-25 15:46:13.964470+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9095a83710'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=True),
    sa.Column('domain_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Unicode(length=200), nullable=True),
    sa.Column('founded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('user_contact',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Unicode(length=50), nullable=False),
    sa.Column('last_name', sa.Unicode(length=50), nullable=False),
    sa.Column('birth_day', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('contact',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('cell_phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Unicode(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_contact.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('user_company',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_contact.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company')
    op.drop_table('contact')
    op.drop_table('user_contact')
    op.drop_table('company')
    # ### end Alembic commands ###
