version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9.5
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - module_9_rabbitmq_data:/var/lib/rabbitmq/
        - module_9_rabbitmq_log:/var/log/rabbitmq
    networks:
        # to add more rabbitmq
        - rabbitmq_go_net
  mongo_db:
    image: mongo:5.0.2
    container_name: 'mongo_db'
    ports:
      - 27017:27017
    environment:
      MONGODB_USER: "mongo_admin"
      MONGODB_PASS: "qwe123"
      MONGODB_DATABASE: "movies_db"
    volumes:
      - module_9_mongo_db:/data/db
  redis:
    image: redis:6.2.5
    container_name: 'module_10_redis'
    ports:
      - 6379:6379

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  module_9_rabbitmq_data:
  module_9_rabbitmq_log:
  module_9_mongo_db: